### PR TITLE
Small Improvement in the async chat response code.

### PR DESCRIPTION
**Pull request by ssojoodi**
- [x] I understand that this repository is auto-generated and my pull request may not be merged

## Changes being requested
Improvement to the README file, specifically the Streaming Responses example. This example runs as is now (circa Python 3.10).

### CODE REVIEW

**Review by rattrayalex — APPROVED** [review]

**Comment by rattrayalex** [comment]
Thank you for the contribution!

**Comment by rattrayalex** [comment]
@ssojoodi there's a merge conflict because we recently fixed the `prompt` -> `model` thing, could you update accordingly?

**Comment by ssojoodi** [comment]
@rattrayalex done. Please have a look. Thanks.

**Comment by rattrayalex** [comment]
Thank you!

**Pull request merged**
