### PR TITLE
Add proxy argument support for openai client

### PR DESCRIPTION
**Pull request by adlternative**
Due to the fact that the openai cli cannot function properly in some poor network environments without a proxy, add a '--proxy' parameter to overcome this difficulty.

v1. support "--proxy" parameter.
v2. give proxy example in README.
v3. supports using multiple "--proxy" parameters.

### CODE REVIEW

**Comment by hallacy** [comment]
Can you give an example of how someone would use this feature if it was merged in?

**Comment by hallacy** [comment]
Yep that makes sense!

I'm about 90% convinced this is a good addition but need a bit more convincing before approving.  I'm struggling a little bit because I'm worried users will think they can add a fully proxy dictionary like in https://requests.readthedocs.io/en/latest/user/advanced/#proxies.  Since it looks like this will only support a string (which is fair), I'm worried this will lead to user confusion.

Thoughts?

**Comment by adlternative** [comment]
> Yep that makes sense!
> 
> I'm about 90% convinced this is a good addition but need a bit more convincing before approving. I'm struggling a little bit because I'm worried users will think they can add a fully proxy dictionary like in https://requests.readthedocs.io/en/latest/user/advanced/#proxies. Since it looks like this will only support a string (which is fair), I'm worried this will lead to user confusion.
> 
> Thoughts?

I change it to use multiple "--proxy" parameter.

In fact, it only supports HTTP or HTTPS, and the dictionary only allows at most one HTTP proxy and at most one HTTPS proxy. It feels like the improvement brought about by this change is very limited.

**Review by hallacy — APPROVED** [review]
That makes sense! Thank you!

**Pull request merged**
