### PR TITLE
fix message attachment typing

### PR DESCRIPTION
**Pull request by yanezh**
- [x] I understand that this repository is auto-generated and my pull request may not be merged

## Changes being requested
Message attachments typing is wrong and can confuse developers.

### CODE REVIEW

**Comment by oleksandr-vonahi** [comment]
@gooroodev would you mind to take a look please?

**Comment by admsev** [comment]
@gooroodev would to mind to take a look please?

**Comment by gooroodev** [comment]
Appreciate being tagged, @admsev!

### 1. Summary of Changes

The pull request makes the following changes to the `message_create_params.py` file:

1. **Imports Adjustment**:
   - Replaces `List` with `Union` in the import statement.
   - Adds imports for `FileSearchToolParam` and `CodeInterpreterToolParam` from the `types.beta` module.

2. **Introduction of `AttachmentToolParam`**:
   - Defines a new type alias `AttachmentToolParam` as a `Union` of `CodeInterpreterToolParam` and `FileSearchToolParam`.

3. **Modification of `Attachment` class**:
   - Changes the `tools` field in the `Attachment` class from `List[Literal["file_search", "code_interpreter"]]` to `Iterable[AttachmentToolParam]`.

### 2. Issues, Bugs, or Typos

#### Issue 1: Typo in Comment
- **Original Code**:
  ```python
  """A list of files attached to the message, and the tools they should be added to."""
  ```
  **Issue**: The comment should use "to which" instead of "they should be added to" to avoid ending the sentence with a preposition.
  **Improved Code**:
  ```python
  """A list of files attached to the message, and the tools to which they should be added."""
  ```

#### Issue 2: Typo in Comment
- **Original Code**:
  ```python
  a maxium of 512 characters long.
  ```
  **Issue**: Typo in "maxium"; should be "maximum".
  **Improved Code**:
  ```python
  a maximum of 512 characters long.
  ```

### 3. General Review of Code Quality and Style

#### Code Quality
- **Consistency**: The code maintains consistency in using type hints and `TypedDict` for defining structured data types.
- **Readability**: The code is generally readable, with clear comments explaining the purpose of each field in the `TypedDict`.

#### Code Style
- **PEP8 Compliance**: The code follows PEP8 guidelines for the most part. However, the import statements could be better organized.
- **Documentation**: The code is well-documented with docstrings explaining each field in the `TypedDict`.

### Suggested Improvements

#### Improvement 1: Organize Imports
- **Current Code**:
  ```python
  from typing import Union, Iterable, Optional
  from typing_extensions import Literal, Required, TypedDict

  from ....types.beta import FileSearchToolParam, CodeInterpreterToolParam
  ```
  **Improved Code**:
  ```python
  from typing import Union, Iterable, Optional
  from typing_extensions import Literal, Required, TypedDict

  from ....types.beta import FileSearchToolParam, CodeInterpreterToolParam
  ```
  **Rationale**: Group imports from the same module together to enhance readability.

#### Improvement 2: Correct the Typo in Comment
- **Current Code**:
  ```python
  a maxium of 512 characters long.
  ```
  **Improved Code**:
  ```python
  a maximum of 512 characters long.
  ```

#### Improvement 3: Improve Comment Clarity
- **Current Code**:
  ```python
  """A list of files attached to the message, and the tools they should be added to."""
  ```
  **Improved Code**:
  ```python
  """A list of files attached to the message, and the tools to which they should be added."""
  ```

Overall, the pull request makes meaningful improvements to the type definitions and maintains good code quality and style. The suggested improvements are minor and aim to enhance readability and correctness.

Yours, [Gooroo.dev](https://github.com/apps/gooroo-dev). React or reply to let me know what you think!

**Comment by rattrayalex** [comment]
Thanks for the PR! This has been addressed on `main`, so closing.

**Pull request closed without merging**
