### PR TITLE
fixing 2 typos in README.md

### PR DESCRIPTION
**Pull request by didier-durand**
Hi, as title implies: 2 typo fixes in documentation

- [x] I understand that this repository is auto-generated and my pull request may not be merged

### CODE REVIEW

**Comment by pstern-sl** [comment]
Thank you! These repos are generated so we will make the corrections on our side.

**Comment by didier-durand** [comment]
Ok. Thanks for the feedback!

**Comment by didier-durand** [comment]
Will you still accept my PR even if erase by your next generation? That would be nice of you.

**Review by rattrayalex — APPROVED** [review]

**Comment by didier-durand** [comment]
Thank you for approving!

**Review by svnviet — APPROVED** [review]

**Comment by rattrayalex** [comment]
Thanks for the contributions! These changes were added elsewhere.

**Comment by didier-durand** [comment]
Thanks for the feedback!
Didier

**Pull request closed without merging**
