### PR TITLE
Adds DALL-E note to Azure OpenAI in v1 SDK

### PR DESCRIPTION
**Pull request by ashjeanbird**
- [x] I understand that this repository is auto-generated and my pull request may not be merged

## Changes being requested
https://github.com/openai/openai-python/issues/692 
Updates Azure OpenAI with a note warning users that Dall-E is not supported in the v1 SDK yet.

### CODE REVIEW

**Comment by rattrayalex** [comment]
I don't think this is how we'd want to phrase it; better to point to the Azure docs which document a workaround. cc @kristapratico

**Comment by StephenHodgson** [comment]
> Azure docs which document a workaround

link?

**Comment by kristapratico** [comment]
> I don't think this is how we'd want to phrase it; better to point to the Azure docs which document a workaround. cc @kristapratico

Thanks, checking with the team.

> link?

https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/migration?tabs=python%2Cdalle-fix#known-issues

**Comment by ashjeanbird** [comment]
Hey, @rattrayalex & @kristapratico I have added the link and the workaround to reflect the suggested doc changes. Thank you for your review.

**Review by rattrayalex — APPROVED** [review]

**Review by schnerd — APPROVED** [review]

**Comment by rattrayalex** [comment]
Ah, this is now outdated bc azure has some support for dalle3 in the new
sdks

**Comment by schnerd** [comment]
Ah my bad – removing here https://github.com/openai/openai-python/pull/830/files

**Comment by StephenHodgson** [comment]
It's probably fine to keep for now until they actually get it in

**Pull request merged**
