### PR TITLE
feat(api): releases from DevDay; assistants, multimodality, tools, dall-e-3, tts, and more

### PR DESCRIPTION
**Pull request by RobertCraigie**

### CODE REVIEW

**Comment by RobertCraigie** [comment]
Includes a version bump to `v1.1.0`

**Comment by combacsa** [comment]
This may not be inappropriate place to post question, though...

```
import openai
client = openai.Client(api_key="[REDACTED]")
assistant = client.assistants.create(
     name="Math Tutor",
     instructions="You are a personal math tutor. Write and run code to answer math questions.",
     tools=[{"type": "code_interpreter"}],
     model="gpt-4-1106-preview"
)
```

```
NotFoundError: Error code: 404 - {'error': {'message': 'Invalid URL (POST /v1/assistants)', 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

I tried with `pip install -U git+https://github.com/openai/openai-python.git@637556b8c03d24cb63df97d019c72823e2b04f63`, please let me know if I'm doing something wrongly.

**Review by schnerd — APPROVED** [review]

**Comment by chadlieberman-flywire** [comment]
> This may be inappropriate place to post question, though... Just tried to use `beta.assistants` API along with this pull request, following guides available on the pages like [ASSISTANTS - Tools - Code Interpreter](https://platform.openai.com/docs/assistants/tools/code-interpreter?lang=python)
> 
> ```
> import openai
> client = openai.Client(api_key="[REDACTED]")
> assistant = client.beta.assistants.create(
>      name="Math Tutor",
>      instructions="You are a personal math tutor. Write and run code to answer math questions.",
>      tools=[{"type": "code_interpreter"}],
>      model="gpt-4-1106-preview"
> )
> ```
> 
> ```
> NotFoundError: Error code: 404 - {'error': {'message': 'Invalid URL (POST /v1/assistants)', 'type': 'invalid_request_error', 'param': None, 'code': None}}
> ```
> 
> I tried with `pip install -U git+https://github.com/openai/openai-python.git@637556b8c03d24cb63df97d019c72823e2b04f63`, please let me know if I'm doing something wrongly.
> 
> (Maybe I'm just trying it too early?)
> 
> (Updated: Ah, I just read "We'll begin rolling out new features to OpenAI customers starting at 1pm PT today." somewhere on Discord. I'll try it again one hour later. Sorry!)

I'm still getting this error. Using v1.1.0

**Comment by barrenechea** [comment]
There are several `retreival` instead of `retrieval`, FYI!

**Comment by RobertCraigie** [comment]
Thanks @barrenechea! Looking into it.

**Comment by combacsa** [comment]
Just FYI, `openai-node` seems to have similar issue(`retreival` instead of `retrieval`). https://github.com/openai/openai-node/blob/d4d46873ce3bf9193c8328cc019057fbb124f783/src/resources/beta/assistants/assistants.ts#L158

**Comment by RobertCraigie** [comment]
Yes both the Node SDK and the Python SDK are generated from the same source, the [OpenAI openapi spec](https://github.com/openai/openai-openapi). Fixes coming to both shortly.

**Pull request merged**
